version: '3'

# NOTE This compose file is meant to be run under a POSIX environment and as such treats volumes thus.
# If this does not work, please feel free to change that.
# ----------------------------------------------------------------------------------------------------------------------
# !!! These services are just meant to make your setup easier, _and in no way suggest that you have to use them_ !!!
# You are free to remove the ones you do not need (and you will likely not need all of them), but the `backend`
# service must remain to run the app.
#
# All ${VARIABLES} are taken from the top .env file in this directory.
# App ----------------------------------------------------------------------------------------------------------------
# client:
#   build: client/
#   volumes:
#     - './client:/code'
#   # host_port_that_your_OS_sees:port_your_container_exposes
#   ports:
#     - '${CLIENT_HOST_PORT}:${CLIENT_CONTAINER_PORT}'
#   stdin_open: true # react native bug, needs this open
#   command: './docker.start.sh'
# Services
services:
  mongo:
    image: 'mongo:4.2.6'
    expose:
      - ${MONGODB_PORT}
    volumes:
      - './.docker-data/mongo:/data/db'

  container_service:
    build: backend/container_service
    ports:
      - '${CONTAINER_SERVICE_HOST_PORT}:${CONTAINER_SERVICE_CONTAINER_PORT}'

    environment:
      PORT: ${CONTAINER_SERVICE_CONTAINER_PORT}
      INVENTORY_SERVICE_BASE_ROUTE: 'http://inventory_service:${INVENTORY_SERVICE_CONTAINER_PORT}'
      CATEGORY_SERVICE_BASE_ROUTE: 'http://category_service:${CATEGORY_SERVICE_CONTAINER_PORT}'
      CONTAINERS_DB_URI: 'mongodb://mongo:${MONGODB_PORT}/container'

    depends_on:
      - mongo

  inventory_service:
    build: backend/inventory_service
    ports:
      - '${INVENTORY_SERVICE_HOST_PORT}:${INVENTORY_SERVICE_CONTAINER_PORT}'

    environment:
      PORT: ${INVENTORY_SERVICE_CONTAINER_PORT}
      INVENTORY_DB_URI: 'mongodb://mongo:${MONGODB_PORT}/inventory'
      CATEGORY_SERVICE_BASE_ROUTE: 'http://category_service:${CATEGORY_SERVICE_CONTAINER_PORT}'

    depends_on:
      - mongo

  category_service:
    build: backend/category_service
    ports:
      - '${CATEGORY_SERVICE_HOST_PORT}:${CATEGORY_SERVICE_CONTAINER_PORT}'

    environment:
      PORT: ${CATEGORY_SERVICE_CONTAINER_PORT}
      CATEGORY_DB_URI: 'mongodb://mongo:${MONGODB_PORT}/category'

    depends_on:
      - mongo

networks:
  default:
    driver: bridge
